### ISSUE TITLE
v5.4.4 Fails downloading artifact !

### ISSUE THREAD

**Issue by T0T4R4** [Inedo/inedox-teamcity#34]
Our TC version is TeamCity 10.0.1 (build 42078

The BM extension fails downloading the TC artifact with the given exception message :

NodeJSAPIs2 build #3 successful. TeamCity reports: SuccessImporting artifact "usq.api.internal.zip" from TeamCity...
Attempting to resolve build configuration ID from project and name...
Downloading build types...
Build configuration ID resolved to: NUSQAPI_INTBranch name was specified: masterImporting TeamCity artifact "usq.api.internal.zip" from https://teamcity.test.wawaweewa.com/httpAuth/repository/download/NUSQAPI_INT/lastSuccessful/usq.api.internal.zip?branch=master...
Downloading temp file to "C:\WINDOWS\TEMP\tmp3AEE.tmp"...
The TeamCity request returned a 404 - this could mean that the branch name, build number, or build configuration is invalid.Removing temp file...Unhandled exception: System.Net.WebException: The remote server returned an error: (404) Not Found.

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Inedo.BuildMasterExtensions.TeamCity.TeamCityArtifactImporter.<ImportAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Inedo.BuildMasterExtensions.TeamCity.Operations.ImportTeamCityArtifactOperation.<ExecuteAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Inedo.BuildMaster.Windows.ServiceApplication.Executions.PlanExecuter.DeploymentPlanExecuter.<Inedo-ExecutionEngine-Executer-IExecutionHostEnvironment-ExecuteActionAsync>d__25.MoveNext()`

**Comment by T0T4R4** [comment]
You might want to use the new TC API instead of the old one ?

**Comment by whatatripp** [comment]
Note the error is a 404; "this could mean that the branch name, build number, or build configuration is invalid", so it's hard to tell what the issue is form the error.

Here is the method https://github.com/Inedo/bmx-teamcity/blob/master/TeamCityArtifactImporter.cs#L40

as far as I can tell, we are using their newer REST API endpoint.

**Comment by jrasch** [comment]
We no longer support this version of TeamCity.
